//+build !noasm !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

#include "textflag.h"

TEXT aap·_memcpy(SB), NOSPLIT|NOFRAME, $0-0
	// DI = dst
	// SI = src
	// DX = size
	MOVQ 0(SI), DX
	MOVQ DX, 0(DI)
	MOVQ 8(SI), DX
	MOVQ DX, 8(DI)
	MOVQ 16(SI), DX
	MOVQ DX, 16(DI)
	MOVQ 24(SI), DX
	MOVQ DX, 24(DI)
	RET

TEXT ·_MaddMemcpy(SB), 7, $0

	MOVQ arg1+0(FP), DI
	MOVQ arg2+8(FP), SI
	MOVQ arg3+16(FP), DX
	MOVQ arg4+24(FP), CX
	WORD $0x8949; BYTE $0xce       // mov    r14, rcx
	WORD $0x8949; BYTE $0xd7       // mov    r15, rdx
	WORD $0x8949; BYTE $0xf4       // mov    r12, rsi
	WORD $0x8948; BYTE $0xfb       // mov    rbx, rdi
	LONG $0x000200ba; BYTE $0x00   // mov    edx, 512
	WORD $0x894c; BYTE $0xe7       // mov    rdi, r12
	WORD $0x8948; BYTE $0xde       // mov    rsi, rbx
	CALL aap·_memcpy(SB)
	LONG $0x000200ba; BYTE $0x00   // mov    edx, 512
	WORD $0x894c; BYTE $0xff       // mov    rdi, r15
	WORD $0x8948; BYTE $0xde       // mov    rsi, rbx
	CALL aap·_memcpy(SB)
	LONG $0x0310fcc5               // vmovups    ymm0, [rbx]
	LONG $0x107cc1c4; WORD $0x240c // vmovups    ymm1, [r12]
	LONG $0xa87dc2c4; BYTE $0x0f   // vfmadd213ps    ymm1, ymm0, [r15]
	LONG $0x117cc1c4; BYTE $0x0e   // vmovups    [r14], ymm1
	VZEROUPPER
	RET
