//+build !noasm !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

TEXT ·_MaddArgs10(SB), 7, $0

    MOVQ arg1+0(FP), DI          // movq    0x8(%rsp), %rdi
    MOVQ arg2+8(FP), SI          // movq    0x10(%rsp), %rsi
    MOVQ arg3+16(FP), DX         // movq    0x18(%rsp), %rdx
    MOVQ arg4+24(FP), CX         // movq    0x20(%rsp), %rcx
    MOVQ arg5+32(FP), R8         // movq    0x28(%rsp), %r8
    MOVQ arg6+40(FP), R9         // movq    0x30(%rsp), %r9
    LONG $0x24448b48; BYTE $0x38 // mov    rax, 0x38[rsp] /* qword [rbp + 16] */
    LONG $0x245c8b48; BYTE $0x40 // mov    rbx, 0x40[rsp] /* qword [rbp + 24] */
    LONG $0x245c8b4c; BYTE $0x48 // mov    r11, 0x48[rsp] /* qword [rbp + 32] */
    LONG $0x24548b4c; BYTE $0x50 // mov    r10, 0x50[rsp] /* qword [rbp + 40] */
    LONG $0x0710fcc5             // vmovups    ymm0, [rdi]
    LONG $0x0e10fcc5             // vmovups    ymm1, [rsi]
    LONG $0x1110fcc5             // vmovups    ymm2, [rcx]
    LONG $0x107cc1c4; BYTE $0x19 // vmovups    ymm3, [r9]
    LONG $0x2310fcc5             // vmovups    ymm4, [rbx]
    LONG $0xa87de2c4; BYTE $0x0a // vfmadd213ps    ymm1, ymm0, [rdx]
    LONG $0xa86dc2c4; BYTE $0x08 // vfmadd213ps    ymm1, ymm2, [r8]
    LONG $0xa865e2c4; BYTE $0x08 // vfmadd213ps    ymm1, ymm3, [rax]
    LONG $0xa85dc2c4; BYTE $0x0b // vfmadd213ps    ymm1, ymm4, [r11]
    LONG $0x117cc1c4; BYTE $0x0a // vmovups    [r10], ymm1
    VZEROUPPER
    RET
