//+build !noasm !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

TEXT ·_MaddArgs10(SB), $40-80

	MOVQ vec1+0(FP), DI
	MOVQ vec2+8(FP), SI
	MOVQ vec3+16(FP), DX
	MOVQ vec4+24(FP), CX
	MOVQ vec5+32(FP), R8
	MOVQ vec6+40(FP), R9
	MOVQ vec7+48(FP), R10
	MOVQ vec8+56(FP), R11
	MOVQ vec9+64(FP), R12
	MOVQ result+72(FP), R13
	ADDQ $8, SP
	MOVQ R13, 24(SP)
	MOVQ R12, 16(SP)
	MOVQ R11, 8(SP)
	MOVQ R10, 0(SP)

	LONG $0x24548b4c; BYTE $0x18 // mov    r10, qword 24[rsp] /* [rbp + 40] */
	LONG $0x245c8b4c; BYTE $0x10 // mov    r11, qword 16[rsp] /* [rbp + 32] */
	LONG $0x24048b48             // mov    rax, qword 0[rsp] /* [rbp + 16] */
	LONG $0x245c8b48; BYTE $0x08 // mov    rbx, qword 8[rsp] /* [rbp + 24] */
	LONG $0x0710fcc5             // vmovups    ymm0, yword [rdi]
	LONG $0x0e10fcc5             // vmovups    ymm1, yword [rsi]
	LONG $0x1110fcc5             // vmovups    ymm2, yword [rcx]
	LONG $0x107cc1c4; BYTE $0x19 // vmovups    ymm3, yword [r9]
	LONG $0x2310fcc5             // vmovups    ymm4, yword [rbx]
	LONG $0xa87de2c4; BYTE $0x0a // vfmadd213ps    ymm1, ymm0, yword [rdx]
	LONG $0xa86dc2c4; BYTE $0x08 // vfmadd213ps    ymm1, ymm2, yword [r8]
	LONG $0xa865e2c4; BYTE $0x08 // vfmadd213ps    ymm1, ymm3, yword [rax]
	LONG $0xa85dc2c4; BYTE $0x0b // vfmadd213ps    ymm1, ymm4, yword [r11]
	LONG $0x117cc1c4; BYTE $0x0a // vmovups    yword [r10], ymm1
	SUBQ $8, SP
	VZEROUPPER
	RET
