//+build !noasm !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

TEXT ·_MultiplyAndAdd(SB), 7, $0

    MOVQ arg1+0(FP), DI
    MOVQ arg2+8(FP), SI
    MOVQ arg3+16(FP), DX
    MOVQ arg4+24(FP), CX
    LONG $0x0710fcc5             // vmovups    ymm0, [rdi]
    LONG $0x0e10fcc5             // vmovups    ymm1, [rsi]
    LONG $0xa87de2c4; BYTE $0x0a // vfmadd213ps    ymm1, ymm0, [rdx]
    LONG $0x0911fcc5             // vmovups    [rcx], ymm1
    VZEROUPPER
    RET
